catalog:
  '@antfu/eslint-config': ^6.7.3
  '@electron-toolkit/preload': ^3.0.2
  '@moeru/std': 0.1.0-beta.18
  '@types/node': ^25.6.0
  '@vitest/browser-playwright': ^4.1.5
  '@vitest/coverage-v8': ^4.1.5
  '@vitest/web-worker': ^4.1.5
  bumpp: ^10.4.1
  crossws: ^0.4.5
  eslint: ^9.39.4
  nanoid: ^5.1.9
  picomatch: ^4.0.4
  playwright: ^1.59.1
  taze: ^19.11.0
  tsdown: ^0.21.10
  tsx: ^4.21.0
  typescript: ^5.9.3
  unplugin-unused: ^0.5.7
  vite: ^7.3.2
  vitest: ^4.1.5

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - electron
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
