catalog:
  '@antfu/eslint-config': ^6.7.3
  '@electron-toolkit/preload': ^3.0.2
  '@moeru/std': 0.1.0-beta.18
  '@types/node': ^25.9.1
  '@vitest/browser-playwright': ^4.1.6
  '@vitest/coverage-v8': ^4.1.6
  '@vitest/web-worker': ^4.1.6
  bumpp: ^11.1.0
  crossws: ^0.4.5
  eslint: ^9.39.4
  nanoid: ^5.1.11
  picomatch: ^4.0.4
  playwright: ^1.60.0
  taze: ^19.13.0
  tsdown: ^0.22.0
  tsx: ^4.22.3
  typescript: ^5.9.3
  unplugin-unused: ^0.5.7
  vite: ^8.0.13
  vitest: ^4.1.6

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - electron
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
