allowBuilds:
  electron: true
  esbuild: true

minimumReleaseAge: 4320

catalog:
  '@antfu/eslint-config': ^9.2.0
  '@electron-toolkit/preload': ^3.0.2
  '@moeru/std': 0.1.0-beta.20
  '@tauri-apps/api': ^2.11.1
  '@types/node': ^25.9.5
  '@types/picomatch': ^4.0.3
  '@vitest/browser-playwright': ^4.1.10
  '@vitest/coverage-v8': ^4.1.10
  '@vitest/web-worker': ^4.1.10
  bumpp: ^12.1.1
  crossws: ^0.4.10
  eslint: ^10.8.0
  hono: ^4.13.0
  nanoid: ^6.0.1
  picomatch: ^4.0.5
  playwright: ^1.62.1
  taze: ^19.17.2
  tsdown: ^0.22.14
  tsx: ^4.23.8
  typescript: ^6.0.3
  unplugin-unused: ^0.6.0
  vite: ^8.2.0
  vitest: ^4.1.10

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - electron
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
